ALTER TYPE content_type ADD VALUE 'JOURNALISM';
ALTER TYPE content_type ADD VALUE 'THERAPISM';
ALTER TYPE content_type ADD VALUE 'IT';
ALTER TYPE content_type ADD VALUE 'HARDWARE ENGINEERING';
ALTER TYPE content_type ADD VALUE 'DATA ANALYTICS';
ALTER TYPE content_type ADD VALUE 'MEDICAL';
ALTER TYPE content_type ADD VALUE 'PHILOSOPHY';
ALTER TYPE content_type ADD VALUE 'WRITING';
ALTER TYPE content_type ADD VALUE 'LANGUAGE AND TRANSLATIONS';